### ISSUE TITLE
Bug with Main Menu and Pause Menu

### ISSUE THREAD

**Issue by Konstantin-Bogdanoski** [Konstantin-Bogdanoski/VP_Project_2019#5]
When you start playing and decide to stop and go back to the main menu, if you click **ESC** you will get the pause menu once again, and you are unable to close it. **Easy to replicate the Bug.**

**Steps:**
**1.** Open game
**2.** Start New Game
**3.** Choose plane
**4.** Start playing
**5.** Pause the game (Click ESC)
**6.** Quit to Main Menu
**7.** Click ESC again
**8.** Voila

**Comment by Bojan-Jovanoski** [comment]
Bug fixed
